### ISSUE TITLE
The method getTrackers has some thing wrong, the column tier can't convert to int.

### ISSUE THREAD

**Issue by ngfchl** [yosemiteyss/qbittorrent_api#13]
**Describe the bug**
The method getTrackers has some thing wrong, the column tier can't convert to int.

**Plugin version**
- Version: [e.g. 1.0.6]

**To Reproduce**

List<Tracker> trackers =
        await controller.client.torrents.getTrackers(hash: torrentInfo.hash!);

**Expected behavior**
"""
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'int?' in type cast
#0      _$TrackerFromJson (package:qbittorrent_api/src/v2/torrents/dto/tracker.g.dart:12:26)
#1      new Tracker.fromJson (package:qbittorrent_api/src/v2/torrents/dto/tracker.dart:20:7)
#2      TorrentsController.getTrackers.<anonymous closure> (package:qbittorrent_api/src/v2/torrents/torrents_controller.dart:80:36)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:39:18)
#8      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#9      TorrentsController.getTrackers (package:qbittorrent_api/src/v2/torrents/torrents_controller.dart:80:49)
<asynchronous suspension>
#10     QBittorrentPage._openTorrentInfoDetail (package:harvest/app/q_bittorrent/view.dart:774:9)
<asynchronous suspension>
"""

**Screenshots**
<img width="1283" alt="image" src="https://github.com/yosemiteyss/qbittorrent_api/assets/45200806/b55889f9-9b08-45e6-a763-724bb615b832">
<img width="1313" alt="image" src="https://github.com/yosemiteyss/qbittorrent_api/assets/45200806/515cdd10-595c-4591-bd83-4af3e193dcc5">

**Comment by yosemiteyss** [comment]
Can you check what string value 'tier' is returning with debugger?

**Comment by ngfchl** [comment]
<img width="1641" alt="image" src="https://github.com/yosemiteyss/qbittorrent_api/assets/45200806/0ca76859-48c7-4f59-9415-dd2faeec2c2b">
OK，I had mark it on the image.

**Comment by yosemiteyss** [comment]
Fixed in 1.0.7.

**Comment by ngfchl** [comment]
thank you very much!
