### ISSUE TITLE
getContents has wrong

### ISSUE THREAD

**Issue by ngfchl** [yosemiteyss/qbittorrent_api#15]
**Describe the bug**
getContents get the file Priority get a strange mistake

**Plugin version**
- Version: [1.0.7]

**To Reproduce**

List<TorrentContents> contents =
        await controller.client.torrents.getContents(hash: torrentInfo.hash!);

I got a not esxit Priority： 4

**Expected behavior**
![image](https://github.com/yosemiteyss/qbittorrent_api/assets/45200806/ddca5c89-b87d-4a9f-a80d-ff82f48ba910)

![image](https://github.com/yosemiteyss/qbittorrent_api/assets/45200806/20fea1f1-6d4f-462b-a4b3-c26454ef3a2f)

**Comment by yosemiteyss** [comment]
Fixed in 1.1.0.
