### ISSUE TITLE
application.getApplicationPreferences() proxy_type error

### ISSUE THREAD

**Issue by xxzj990** [yosemiteyss/qbittorrent_api#21]
**Describe the bug**
get json like -> "proxy_type": "None",

Invalid argument(s): `None` is not one of the supported values: 0, 1, 2, 3, 4, 5

**Plugin version**
- Version: 1.2.0

**To Reproduce**
use qb 4.6.4

**Expected behavior**
Get the correct proxy_type field.

**Screenshots**
None.

**Platform (please complete the following information):**
- OS: Unraid - Docker
- Version: 6.12.10

**Comment by yosemiteyss** [comment]
Fixed in 1.2.1
